# Generated by Django 5.1.7 on 2025-03-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_articletag_articlepage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
